### ISSUE TITLE
error with pytest

### ISSUE THREAD

**Issue by Rozie100** [kokkos/pykokkos#203]
I am running into the following error when I run pytest:
AttributeError: module 'kokkos' has no attribute 'int8'

**Comment by tylerjereddy** [comment]
This isn't really a suitable ticket. When reporting an issue you should always include:

- the exact steps you followed to install `pykokkos-base` followed by `pykokkos`
- the version of each you are using, the version of Python, and so on
- the platform/operating system and architecture you are working on
- the full traceback of the error

When in doubt, you can also check the steps you've used against the steps we use in our CI (continuous integration) tests.

**Comment by Rozie100** [comment]
Thank you,

I already run everything successfully. I am trying to run " python pytest". 

The latest version. python3.8
Linux OS

I am getting the following error:

Traceback (most recent call last):
  File "runtests.py", line 14, in <module>
    from tests import _logging_probe
  File "/home/rozie/pykokkos/tests/_logging_probe.py", line 13, in <module>
    import pykokkos
  File "/home/rozie/pykokkos/pykokkos/__init__.py", line 5, in <module>
    from pykokkos.core import CompilationDefaults, Runtime
  File "/home/rozie/pykokkos/pykokkos/core/__init__.py", line 1, in <module>
    from pykokkos.interface import *
  File "/home/rozie/pykokkos/pykokkos/interface/__init__.py", line 2, in <module>
    from .atomic.atomic_fetch_op import (
  File "/home/rozie/pykokkos/pykokkos/interface/atomic/atomic_fetch_op.py", line 6, in <module>
    from ..views import View
  File "/home/rozie/pykokkos/pykokkos/interface/views.py", line 16, in <module>
    import pykokkos.kokkos_manager as km
  File "/home/rozie/pykokkos/pykokkos/kokkos_manager/__init__.py", line 7, in <module>
    from pykokkos.interface.data_types import DataTypeClass, double
  File "/home/rozie/pykokkos/pykokkos/interface/data_types.py", line 7, in <module>
    class DataType(Enum):
  File "/home/rozie/pykokkos/pykokkos/interface/data_types.py", line 8, in DataType
    int8 = kokkos.int8
AttributeError: module 'kokkos' has no attribute 'int8'
