### ISSUE TITLE
BUG: thread/reference safety for views or kernels?

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#34]
I was in the middle of typing up a more detailed description of the problem when my power went out, but I'll try to provide some more concise info for my issue here from what I can do on my laptop.

Working on the `develop` branch, if we simplify `tests/test_ufuncs.py` to only contain this while debugging: 

```python
import pykokkos as pk

import numpy as np
from numpy.testing import assert_allclose
import pytest

@pytest.mark.parametrize("pk_ufunc, numpy_ufunc", [
        (pk.reciprocal, np.reciprocal),
])
@pytest.mark.parametrize("pk_dtype, numpy_dtype", [
        (pk.double, np.float64),
        (pk.float, np.float32),
])
def test_1d_exposed_ufuncs_vs_numpy(pk_ufunc,
                                    numpy_ufunc,
                                    pk_dtype,
                                    numpy_dtype):
    # test the ufuncs we have exposed in the pk namespace
    # vs. their NumPy equivalents
    expected = numpy_ufunc(np.arange(10, dtype=numpy_dtype))

    view: pk.View1d = pk.View([10], pk_dtype)
    view[:] = np.arange(10, dtype=numpy_dtype)
    actual = pk_ufunc(view=view)
    assert_allclose(actual, expected)
```

The test will pass just fine as-is with `python runtests.py -t tests/test_ufuncs.py`. But, if we substantially increase the number of repeats like this (example only, I will use far more repeats in my testing):

```diff
 @pytest.mark.parametrize("pk_ufunc, numpy_ufunc", [
         (pk.reciprocal, np.reciprocal),
 ])
 @pytest.mark.parametrize("pk_dtype, numpy_dtype", [
         (pk.double, np.float64),
         (pk.float, np.float32),
+        (pk.float, np.float32),
+        (pk.float, np.float32),
+        (pk.float, np.float32),
+        (pk.float, np.float32),
+        (pk.float, np.float32),
 ])
 def test_1d_exposed_ufuncs_vs_numpy(pk_ufunc,
                                     numpy_ufunc,
```

I will start getting non-deterministic test failure ratios:

- `35 failed, 667 passed`
- `21 failed, 681 passed`
- `17 failed, 685 passed`

This seems bad--the kernel/workunit for `reciprocal` is incredibly simple, so my initial suspicion is something related to kernel/view thread safety maybe? 

The nature of the failure seems to be a somewhat-stochastic restoration of the original view values:

```
E       
E       x and y +inf location mismatch:
E        x: array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)
E        y: array([     inf, 1.      , 0.5     , 0.333333, 0.25    , 0.2     ,
E              0.166667, 0.142857, 0.125   , 0.111111], dtype=float32)
```

This is a simplified reproducer of a more complex situation that arose while I was adding more tests for the new `sqrt` `pykokkos` ufunc in feature branch `treddy_more_1d_ufuncs`. In that case, separate parametrized pytest tests were interfering with each other in bizarre ways by resetting the values in views to their originals. I also had higher failure ratios for the `sqrt` ufunc with high repeat counts. 

So, my first question is--is this a known issue? I can reproduce on two separate machines at least.

**Comment by tylerjereddy** [comment]
Here is a simplified reproducer that removes `pytest` from the equation completely, and also shouldn't use Python threading unless `pykokkos` is doing that under the hood:

```python
import pykokkos as pk

import numpy as np
from numpy.testing import assert_allclose


def main():
    expected = np.reciprocal(np.arange(10, dtype=np.float32))
    view: pk.View1d = pk.View([10], pk.float)
    print("view A:", view)
    view[:] = np.arange(10, dtype=np.float32)
    print("view B:", view)
    actual = pk.reciprocal(view=view)
    print("actual:", actual)
    assert_allclose(actual, expected)


if __name__ == "__main__":
    for i in range(1, 1000):
        main()
        print(f"succeeded at iteration {i}")

```

This reliably fails after succeeding on the first iteration, which to me is completely unexpected:

```
view A: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
view B: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
actual: [       inf 1.         0.5        0.33333334 0.25       0.2
 0.16666667 0.14285715 0.125      0.11111111]
succeeded at iteration 1
view A: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
view B: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
actual: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Traceback (most recent call last):
  File "/home/tyler/LANL/rough_work/pykokkos/issue_34/test.py", line 20, in <module>
    main()
  File "/home/tyler/LANL/rough_work/pykokkos/issue_34/test.py", line 15, in main
    assert_allclose(actual, expected)
  File "/home/tyler/python_310_pykokkos_work/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/tyler/python_310_pykokkos_work/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 771, in assert_array_compare
    flagged |= func_assert_same_pos(x, y,
  File "/home/tyler/python_310_pykokkos_work/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 745, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

x and y +inf location mismatch:
 x: array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)
 y: array([     inf, 1.      , 0.5     , 0.333333, 0.25    , 0.2     ,
       0.166667, 0.142857, 0.125   , 0.111111], dtype=float32)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

Aborted (core dumped)

```

As far as threading, it looks like using threads causes issues different from those reported here, so that's probably a separate matter/something to document if each thread needs an explicit execution space setup:

```python
from concurrent.futures import ThreadPoolExecutor

import pykokkos as pk

import numpy as np
from numpy.testing import assert_allclose


def main():
    expected = np.reciprocal(np.arange(10, dtype=np.float32))
    view: pk.View1d = pk.View([10], pk.float)
    print("view A:", view, flush=True)
    view[:] = np.arange(10, dtype=np.float32)
    print("view B:", view, flush=True)
    actual = pk.reciprocal(view=view)
    print("actual:", actual, flush=True)
    assert_allclose(actual, expected)
    return actual


if __name__ == "__main__":
    with ThreadPoolExecutor(max_workers=8) as executor:
        for i in range(1, 1000):
            print("launching thread:", i)
            future = executor.submit(main)
            result = future.result()
            print("result:", result)
            print(f"succeeded at iteration {i}")

```

```
launching thread: 1
/home/tyler/LANL/rough_work/pykokkos/issue_34/test.py:10: RuntimeWarning: divide by zero encountered in reciprocal
  expected = np.reciprocal(np.arange(10, dtype=np.float32))
Traceback (most recent call last):
  File "/home/tyler/LANL/rough_work/pykokkos/issue_34/test.py", line 26, in <module>
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tyler/LANL/rough_work/pykokkos/issue_34/test.py", line 11, in main
    view: pk.View1d = pk.View([10], pk.float)
  File "/home/tyler/github_projects/pykokkos/pykokkos/interface/views.py", line 181, in __init__
    self._init_view(shape, dtype, space, layout, trait, array)
  File "/home/tyler/github_projects/pykokkos/pykokkos/interface/views.py", line 262, in _init_view
    self.array = kokkos.array("", shape, None, None, self.dtype.value, space.value, layout.value, trait.value)
  File "/home/tyler/python_310_pykokkos_work/lib/python3.10/site-packages/pykokkos_base-0.0.7-py3.10-linux-x86_64.egg/kokkos/utility.py", line 197, in array
    return getattr(lib, _name)(label if array is None else array, shape)
RuntimeError: Constructing View and initializing data with uninitialized execution space
Traceback functionality not available
```

**Comment by tylerjereddy** [comment]
This should have been fixed by gh-36.
