### ISSUE TITLE
Ability to switch execution spaces?

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#5]
I have a simple `pykokkos` script like below, using the simple "function based" approach to `pykokkos`, that produces a rather cryptic error messages if I attempt to switch between execution spaces in the same module, which might be useful for interwoven benchmarking for example:

```python
import pykokkos as pk


@pk.workunit
def hello(i: int):
    pk.printf("Hello from i = %d\n", i)


if __name__ == "__main__":
    pk.set_default_space(pk.OpenMP)
    pk.parallel_for(10, hello)
    pk.set_default_space(pk.Cuda)
    pk.parallel_for(10, hello)
```
 
Error message:

<details>

```
[treddy@cn661 pykokkos_internal]$ python sample_benchmarks/sqrt_compare.py 
INFO:root:translation 0.0019483482465147972
INFO:root:compilation 8.89616567734629
Hello from i = 5
Hello from i = 7
Hello from i = 1
Hello from i = 4
Hello from i = 8
Hello from i = 6
Hello from i = 2
Hello from i = 3
Hello from i = 9
Hello from i = 0
Traceback (most recent call last):
  File "sample_benchmarks/sqrt_compare.py", line 13, in <module>
    pk.parallel_for(10, hello)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/interface/parallel_dispatch.py", line 126, in parallel_for
    runtime_singleton.runtime.run_workunit(
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/runtime.py", line 81, in run_workunit
    members: Optional[PyKokkosMembers] = self.compiler.compile_object(module_setup, policy.space, km.is_uvm_enabled())
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/compiler.py", line 138, in compile_object
    self.compile_entity(module_setup.main, module_setup, entity, parser.get_classtypes(), space, force_uvm)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/compiler.py", line 195, in compile_entity
    functor, bindings = translator.translate(entity, classtypes)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/translators/static.py", line 57, in translate
    self.pk_members.extract(entity, classtypes)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/translators/members.py", line 77, in extract
    self.fields, self.views = self.get_params(AST, source, param_begin, pk_import)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/translators/members.py", line 197, in get_params
    visitor.visit(functiondef)
  File "/vast/home/treddy/github_projects/spack/opt/spack/linux-centos8-cascadelake/gcc-9.4.0/python-3.8.12-v3zf3eymsvk5kys3vynoj7xljq4ensj2/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/visitors/parameter_visitor.py", line 39, in visit_FunctionDef
    self.visit(node.args)
  File "/vast/home/treddy/github_projects/spack/opt/spack/linux-centos8-cascadelake/gcc-9.4.0/python-3.8.12-v3zf3eymsvk5kys3vynoj7xljq4ensj2/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/visitors/parameter_visitor.py", line 56, in visit_arguments
    self.visit(a)
  File "/vast/home/treddy/github_projects/spack/opt/spack/linux-centos8-cascadelake/gcc-9.4.0/python-3.8.12-v3zf3eymsvk5kys3vynoj7xljq4ensj2/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/visitors/parameter_visitor.py", line 71, in visit_arg
    self.error(node, "Type is not supported")
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/visitors/parameter_visitor.py", line 82, in error
    visitors_util.error(self.src, self.debug, node, message)
  File "/vast/home/treddy/github_projects/pykokkos/pykokkos/core/visitors/visitors_util.py", line 119, in error
    print(f"\n\033[31m\033[01mError on line {node.lineno} \033[0m: {message}")
AttributeError: 'arg' object has no attribute 'lineno'
[treddy@cn661 pykokkos_internal]$ 
```

</details>

If I switch the ordering to do `Cuda` execution space first, then the error happens first, then I get the correct OpenMP input after.

If I use either execution space on their own, things work just fine. I can also switch between execution spaces just fine as long as I don't actually actually execute within them, i.e.,

```python
if __name__ == "__main__":
    pk.set_default_space(pk.OpenMP)
    #pk.parallel_for(10, hello)
    pk.set_default_space(pk.Cuda)
    pk.parallel_for(10, hello)
```

If interwoven executions are forbidden, perhaps there should be a clear error message about that? Otherwise, maybe there's a bug somewhere?

**Comment by NaderAlAwar** [comment]
Thanks for reporting this! Interwoven executions are allowed, this is a bug that was specific to the function based style. I pushed a fix to `develop`, so it should work now. That said you might run into issues later on when you use views with multiple execution spaces, as the memory layouts and memory spaces of the views will depend on the value of the default execution space when they are created. Let me know if that happens.

**Comment by tylerjereddy** [comment]
@NaderAlAwar I confirmed the issue is fixed on latest `develop` on one of our Volta nodes, thanks.

![image](https://user-images.githubusercontent.com/7903078/154537395-e5e33d75-2b32-4a62-81c8-48cc1c8d49ef.png)
